language: node_js
before_install:
    - phantomjs --version
    - npm install -g grunt-cli grunt-init bower
    - bower install
branches:
  only:
  - master
node_js:
- '0.10'
before_script:
- git config --global user.name "{{author_name}}"
- git config --global user.email "{{author_email}}"
- export REPO_URL="https://$GH_TOKEN@{{ghpage_repo|replace("https://", "")}}"

script:
{% if not settings %}
- grunt-init config
{% endif %}
- npm test
after_success:
{% if settings %}
- node crawl
- grunt sitemap
- git remote add blogist $REPO_URL
- git checkout -B {{branch}}
- git rm .travis.yml -f
- git add sitemap.xml index.html javascripts bower_components -f
- git add CNAME
- git add gist atom.xml -f
- git commit -am 'publi:ship:'
- git push blogist {{branch}} -f -q
{% endif%}
